clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
    when:
      event: push

pipeline:
  test:
    # https://github.com/euantorano/docker-zig
    image: euantorano/zig:master
    commands:
      - apk add --update make
      - make fmt test
    when:
      - event: push
