baseURL = 'https://zigcli.liujiacai.net/'
languageCode = 'en-us'
title = 'Zigcli'
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

# [languages.zh]
#   languageName = 'Chinese'
#   contentDir = 'content.zh'
#   weight = 2

[params]
  BookTheme = 'auto'
  BookRepo = 'https://github.com/jiacai2050/zigcli'
  BookEditPath = 'edit/main/docs'
  BookDateFormat = '2006-01-02T15:04:05 -0700'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'