steps:
  - name: zig
    image: ziglings/ziglang:latest
    pull: true
    commands:
      - zig version
      - zig fmt --check .
      - zig build test --summary all

when:
  - event: [push, cron]
    cron: ci*
