name: Build binary

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.zig"
      - ".github/workflows/CI.yml"
  push:
    branches:
      - main
    paths:
      - "**.zig"
      - ".github/workflows/binary.yml"

env:
  ZIG_VERSION: 0.13.0

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets:
          - "x86-windows"
          - "x86_64-windows"
          - "aarch64-windows"
          - "x86-linux"
          - "x86_64-linux"
          - "arm-linux-musleabi"
          - "aarch64-linux"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: Set Environment Variables
        run: |
          echo "BUILD_DATE=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_ENV
      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.targets }} -Doptimize=ReleaseSafe \
          -Dgit_commit=${{ github.head_ref }}-${{ github.sha }} \
          -Dbuild_date=${{ env.BUILD_DATE }} -Dis_ci=true
          # https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
          tar -cvf zigcli.tar zig-out/bin/
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: zigcli-${{ matrix.targets }}
          path: zigcli.tar

  build-macos:
    timeout-minutes: 10
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        targets:
          - "x86_64-macos"
          - "aarch64-macos"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: mlugg/setup-zig@v1
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Set Environment Variables
        run: |
          echo "BUILD_DATE=$(date +'%Y-%m-%dT%H:%M:%S%z')" >> $GITHUB_ENV
          echo "GIT_INFO=${{ github.head_ref }}-${{ github.sha }}" >> $GITHUB_ENV
      - name: Build
        run: |
          zig build -Dtarget=${{ matrix.targets }} -Doptimize=ReleaseSafe \
          -Dgit_commit=${{ env.GIT_INFO }} \
          -Dbuild_date=${{ env.BUILD_DATE }} -Dis_ci=true
          # https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
          tar -cvf zigcli-${{ env.GIT_INFO }}.tar zig-out/bin/
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: zigcli-${{ matrix.targets }}-${{ env.GIT_INFO }}
          path: zigcli-${{ env.GIT_INFO }}.tar
